#!/bin/bash
#
# scripts/findings-backfill-pr.sh — open a single PR with all findings
# generated by `corpus-findings extract-all`.
#
# Run this on the mini after the backfill process finishes:
#
#   ssh afisk@mini 'cd ~/code/circumvention-corpus && bash scripts/findings-backfill-pr.sh'
#
# What it does:
#   1. Refuses to run if extract-all is still in progress.
#   2. Counts new + modified finding YAMLs in corpus/findings/.
#   3. Recovers to main, pulls latest, branches `auto-ingest/findings-
#      backfill-YYYY-MM-DD`.
#   4. git add + commits + pushes; opens a PR labeled `auto-ingest`.
#
# The PR is one big commit by design: all findings come from the same
# pipeline (corpus-findings + claude-sonnet-4-6) with the same
# extracted_by stamp. Reviewers should sample-check a handful, not read
# every entry. The schema-integrity test in CI already validates
# taxonomy IDs and paper references for every finding.

set -euo pipefail

cd "$(dirname "$0")/.." || exit 1
REPO=$(pwd)

stamp() { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)]" "$@"; }

# 1. Refuse if backfill is still running.
if pgrep -fq "corpus-findings extract-all" 2>/dev/null; then
    stamp "ERROR: corpus-findings extract-all is still running. Wait for it to finish."
    stamp "Tail the log: tail -f /tmp/findings-backfill.log"
    exit 1
fi

# 2. Count new + modified finding files in corpus/findings/.
NEW=$(git ls-files --others --exclude-standard corpus/findings/ 2>/dev/null | wc -l | tr -d ' ')
MOD=$(git diff --name-only -- corpus/findings/ 2>/dev/null | wc -l | tr -d ' ')
TOTAL=$((NEW + MOD))
if [[ "$TOTAL" -eq 0 ]]; then
    stamp "no new or modified findings to commit; nothing to do"
    exit 0
fi
stamp "$NEW new + $MOD modified finding YAMLs ready to commit"

# 3. Set up branch from main.
git config user.name  "circumvention-corpus-bot"
git config user.email "bot@lantern.io"

stamp "checking out main + pulling latest"
git checkout --quiet main
git pull --ff-only --quiet origin main

DATE=$(date -u +%Y-%m-%d)
BRANCH="auto-ingest/findings-backfill-$DATE"

# Delete any stale local branch with the same name; the remote branch
# (if it exists from a previous attempt) will be force-pushed below
# only if --force is set. Default: bail and let a human resolve.
if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
    stamp "local branch $BRANCH already exists; aborting (delete it first if you want to redo)"
    exit 1
fi

stamp "creating branch $BRANCH"
git checkout --quiet -b "$BRANCH"

# 4. Stage + commit. Cap the commit message; details are in the PR body.
stamp "staging + committing"
git add corpus/findings/
git commit -m "Auto-ingest: full-text findings backfill ($TOTAL findings)

Findings extracted via 'corpus-findings extract-all' from the full PDF
text of each paper (pdftotext -layout → claude-sonnet-4-6). Each file
is tagged extracted_by: claude-sonnet-4-6 and named
  <paper-id>__<finding-slug>.yaml

Review by sampling — the corpus-mcp integrity test already validates
that every taxonomy ID resolves and every paper reference exists.

Generated by scripts/findings-backfill-pr.sh on $DATE." \
    --quiet

# 5. Push + open PR.
stamp "pushing $BRANCH"
git push --quiet -u origin "$BRANCH"

stamp "opening PR"
PR_BODY="# Findings backfill — $DATE

Automated full-text findings extraction across the corpus.

**$TOTAL finding YAML(s)** generated by \`corpus-findings extract-all\`:
- pdftotext -layout to plain text from each paper's PDF
- claude-sonnet-4-6 via \`claude -p\`, prompt-cached taxonomy
- 3-5 findings per paper, tagged \`extracted_by: claude-sonnet-4-6\`

Review by sampling rather than reading every entry. The
\`corpus-mcp\` integrity test in CI validates taxonomy IDs and paper
references for every finding. Safe to merge once a handful of
spot-checks look right.

To redo or extend: \`corpus-findings extract --paper <id> --force\`
re-runs extraction on a single paper; \`extract-all\` skips papers
that already have findings."

gh pr create \
    --title "Auto-ingest: findings backfill ($DATE — $TOTAL findings)" \
    --body "$PR_BODY" \
    --label auto-ingest \
    --base main --head "$BRANCH"

# Reset to main so the next launchd run starts clean.
git checkout --quiet main
stamp "done"
